version: '2'
services:
  drone-server:
    image: drone/drone:1
    container_name: drone-server
    ports:
      - "${DRONE_WEB_PORT}:80"
      - 443:443
    volumes:
      - ./droneDBData:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone:/var/lib/drone/
   

    restart: always
    # detach: true
    environment:
      # 不確定是幹嘛的
      - DRONE_OPEN=true
      - DRONE_GIT_ALWAYS_AUTH=false                                 # Drone clone 時，是否每次都驗證
      - DRONE_RUNNER_CAPACITY=1                                     # 表示一次可執行 n 個 job
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}                    # http 或者 https 連線設定
      - DRONE_TLS_AUTOCERT=false                                    # 自動生成 ssl 證書，並接受 https 連線，末認為false
      - DRONE_USER_CREATE=username:nazmulb,admin:true               # 可選擇特定帳號為使用者權限
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}                      # Drone URL
      - NGROK_URL_WITHOUT_PROTOCOL=${NGROK_URL_WITHOUT_PROTOCOL}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_GITLAB_URL=${DRONE_GITLAB_URL}
      - DRONE_GITLAB_CLIENT_ID=${DRONE_GITLAB_CLIENT_ID}            # OAuth 的 Application ID
      - DRONE_GITLAB_CLIENT_SECRET=${DRONE_GITLAB_CLIENT_SECRET}    # OAuth 的 Secret
      - DRONE_GITLAB_SERVER=${DRONE_GITLAB_SERVER}                  # Gitlab Server
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true                                       # Log 啟用顏色辨識
      - DRONE_HOST=${DRONE_HOST}
    # environment:
    #   - DRONE_OPEN=true
    #   - DRONE_GIT_ALWAYS_AUTH=false
    #   - DRONE_GITHUB_SERVER=${DRONE_GITHUB_SERVER}
    #   - DRONE_RUNNER_CAPACITY=1
    #   - DRONE_SERVER_PROTO=https
    #   - DRONE_TLS_AUTOCERT=true
    #   - DRONE_USER_CREATE=username:nazmulb,admin:true 
    #   - DRONE_GITHUB=true
    #   - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      
    #   - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
    #   - NGROK_URL_WITHOUT_PROTOCOL=${NGROK_URL_WITHOUT_PROTOCOL}
    #   - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
    #   - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
    #   - DRONE_SECRET=${DRONE_SECRET}
  drone-agent:
    image: drone/agent:1
    container_name: drone-agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=drone-server
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=3
      - DRONE_LOGS_DEBUG=true   # 選擇是否開啟 debug 模式

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=3

 