
CREATE USER IF NOT EXISTS 'mydb_slave_user'@'*' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON * . * TO 'mydb_slave_user'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON * . * TO 'root'@'%' IDENTIFIED BY '123456';
GRANT REPLICATION SLAVE ON * . * TO 'mydb_slave_user'@'%' IDENTIFIED BY '123456';
FLUSH PRIVILEGES;